### PR TITLE
Passthrough location at 3xx status code

### PR DESCRIPTION
**Pull request by vblz**
Also replace GET request by HEAD beacuse the script does not check the response body

### CODE REVIEW

**Comment by vblz** [comment]
I'm using it like
```
http-request deny if !{ var(txn.auth_response_successful) -m bool } !{ var(txn.auth_response_code) eq 303 }
http-request redirect location %[var(txn.auth_response_location)] code 303 if !{ var(txn.auth_response_successful) -m bool } { var(txn.auth_response_code) eq 303 }
```

**Comment by TimWolla** [comment]
That's looking good overall and does not appear to break compatibility :+1: 

However I'm not sure whether we should handle all of 3xx like this. Consider “304 Not Modified”. It does not usually contain a `Location` response header. What do you think?

**Comment by vblz** [comment]
I agree. I'll make some changes now. What do you think should be if the code 3xx was received? Should it be logged or just pass silently?

**Comment by TimWolla** [comment]
> Should it be logged or just pass silently?

Anything that is not explicitly handled should be logged. It indicates that the backend is not compatible with the current version of haproxy-auth-request and requires administrator attention to make sure that it behaves correctly.

e.g. if the backend is sending a 304 for some reason, while it would ordinarily send a 200 the admin needs to be notified of it, because requests are erroneously denied! To be clear: A 304 should be `txn:set_var("txn.auth_response_successful", false)` to fail closed.

**Comment by vblz** [comment]
fixed

**Comment by TimWolla** [comment]
Thanks it's looking good now. I'll do test myself when I have a free minute to make sure we did not miss anything.

**Comment by vblz** [comment]
any remarks?

**Comment by TimWolla** [comment]
> any remarks?

I've did some basic tests with the modified script and it appears to work fine, but I did not yet get around to properly test all of the new behaviour.

**Comment by TimWolla** [comment]
@vblz Okay, I done a few tests. It's working good. Can add the changed behaviour to README or would you rather like me to do this?

**Comment by vblz** [comment]
It would be great if you can do it

**Comment by TimWolla** [comment]
Finally got around to it. Now merged, thanks again for your contribution!

**Pull request merged**
