### PR TITLE
Switch to haproxy-lua-http instead of lua-socket

### PR DESCRIPTION
**Pull request by TimWolla**

### CODE REVIEW

**Comment by mike-code** [comment]
Hi. I was wondering whether this PR addresses some of the known limitations in the socket version?

**Comment by TimWolla** [comment]
> Hi. I was wondering whether this PR addresses some of the known limitations in the socket version?

Depends on the limitations you want to know about.

**Comment by mike-code** [comment]
> > Hi. I was wondering whether this PR addresses some of the known limitations in the socket version?
> 
> Depends on the limitations you want to know about.

I was mainly thinking about the backend not using TLS as it requires a workaround. It's not a big deal at all but I was just trying to get a sneak peek :)

**Comment by TimWolla** [comment]
I did not test this. It might work if the certificate is valid for the IP address of the backend server, because we can't connect to a domain name, only to an IP address. In any case it would require a modification, because `http://` is hardcoded.

**Pull request merged**
